---
title: "Mapping"
author: "Group"
date: "11/10/2020"
output: pdf_document
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,fig.align='center'}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(ggplot2)
library(dplyr)
library(lubridate)
library(rgdal)
library(usmap)
library(sf)
```


### add geom to dataset, for `tmap` or `leaflet` packages
- `county.fips` and `county`is in package `maps`.  
- use `left_join` to merge county's fips with its longitude and latitude

```{r}
data(county.fips)
uscounty=st_as_sf(map('county',plot=F,fill=T))

colnames(county.fips)[2]=colnames(uscounty)[1]
uscounty=left_join(uscounty,county.fips,'ID')
```


```{r}
#initial code
#df_map=df_countywide %>%
#  group_by(declarationYear,fips,incidentType)%>%
#  summarise(projectAmount=sum(projectAmount),totalObligated=sum(totalObligated),.groups="drop")%>%
#  mutate(fips=as.numeric(fips))%>%
#  right_join(x=uscounty,by='fips')

#final code
df_map=df_countywide %>%
  group_by(declarationYear,stateCode,county,fips,incidentType)%>%
  summarise(projectAmount=sum(projectAmount),totalObligated=sum(totalObligated),.groups="drop")%>%
  mutate(fips=as.numeric(fips))%>%
  right_join(x=uscounty,by='fips')
```

### mapping function

```{r}
# write own function for shiny interaction, filter different years and states
countyplot=function(year,state){
  h=df_map%>%filter(declarationYear==year,stateCode==state)
  p1=plot_usmap("county", data = h, values = "projectAmount",include = h$stateCode,color ="red")+
  scale_fill_continuous(low = "white", high = "red", name = "projec Amount", label = scales::comma) +
  theme(legend.position = "right")+  
  labs(title = "US States", subtitle = "Public Assistance Funded Projects Amount")
  
  p2=plot_usmap("county", data = h, values = "totalObligated",include = h$stateCode,color ="blue")+
  scale_fill_continuous(low = "white", high = "blue", name = "total Obligated", label = scales::comma) +
  theme(legend.position = "right")+  
  labs(title = "US States", subtitle = "Federal Share In Dollars")
  
  cowplot::plot_grid(p1,p2,nrow=1)
}

#for example
countyplot(2017,"AL")
```
